// Build script for Netlify deployment
// Generates js/config.js from environment variables

const fs = require('fs');

const razorpayKey = process.env.RAZORPAY_KEY_ID || 'rzp_test_YourTestKeyHere';

const configContent = `/* Auto-generated by build.js — DO NOT EDIT MANUALLY */
const RAZORPAY_CONFIG = {
    KEY_ID: '${razorpayKey}',
};
`;

fs.writeFileSync('js/config.js', configContent);
console.log('✅ config.js generated with Razorpay key');
